<?php

/**
 * Implements hook_permission().
 */
function espace_pro_permission() {
    return array(
        'access espace professionnel' => array(
            'title' => t('Accéder à l\'espace professionnel distributeur'),
        ),
    );
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function espace_pro_ctools_plugin_api($module, $api) {
    if ($module == 'page_manager' && $api == 'pages_default') {
        return array('version' => 1);
    }
}

function espace_pro_menu() {
    $items = array();

    /** TODO
     *  La page d'espace pro.
     *
    $items['espace-professionnel-test'] = array(
        'title' => 'Votre espace professionnel',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('distributeurs_form'),
        'access callback' => 'user_is_logged_in',
        'type' => MENU_CALLBACK,
    );
    */
    return $items;
}